[package]
name = "rustyminitel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

sysinfo = { git = "https://github.com/GuillaumeGomez/sysinfo" }
local-ip = "0.1"

